#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

case "$1" in
    stable)
        # install the latest stable version of home assistant
        pip3 install --force-reinstall homeassistant
        ;;
    beta)
        # install the latest beta version of home assistant
        pip3 install --upgrade --pre homeassistant
        ;;
    dev)
        # install the latest dev version of home assistant
        pip3 install --upgrade git+https://github.com/home-assistant/core.git@dev
        ;;
    version)
        # print the version of home assistant
        python3 -m homeassistant --version
        ;;
    help)
        # print the help message
        echo "Usage: $0 [stable|beta|dev|version|<version>]"
        ;;
    list)
        # list all available versions of home assistant
        pip index versions homeassistant --pre
        ;;                
    *)         
        # if first argument matches a version number, install that version ie 0.115.6 or 0.116.0b0
        if [[ $1 =~ ^[0-9]+\.[0-9]+(\.[0-9]+)?(b[0-9]+)?$ ]]; then
            pip3 install --upgrade homeassistant==$1
        else
            # otherwise print the help message
            echo "Usage: $0 [stable|beta|dev|version|list|<version>]"
        fi
        ;;
esac

