name: Mark stale issues and pull requests

on:
  schedule:
    - cron: "30 1 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - uses: actions/stale@v9
        with:
          any-of-issue-labels: "waiting-for-response"
          days-before-issue-stale: 30
          stale-issue-label: stale
          stale-issue-message: >
            This issue has been automatically marked as abandoned because it has not had
            recent activity. It will be closed if no further activity occurs. Thank you
            for your contributions.
          exempt-issue-labels: "no-stale, bug, documentation"
